# Generated by Django 5.2.3 on 2025-06-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_contactmessage_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
